services:
  reddit-flow:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates:z
      - ./public:/usr/share/nginx/html:z
      - ./certbot/conf:/etc/letsencrypt:z
      - ./certbot/www:/var/www/certbot:z
    restart: unless-stopped

    # See: https://github.com/nginx/docker-nginx/issues/422
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & /docker-entrypoint.d/20-envsubst-on-templates.sh; nginx-debug -g \"daemon off;\"'"

  
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt:z
      - ./certbot/www:/var/www/certbot:z
    restart: unless-stopped